# FILE: omnigraph/servers/millenniumdb.py
"""
Created on 2025-11-25

MillenniumDB SPARQL support
generated by Claude Sonnet 4.5 using

https://gitingest.com/
and the content of
https://github.com/WolfgangFahl/pyomnigraph/issues/14

with the prompt:
    implement #14

@author: wf
"""

from dataclasses import dataclass
from pathlib import Path


from omnigraph.server_config import ServerLifecycleState, ServerStatus
from omnigraph.sparql_server import Response, ServerConfig, ServerEnv, SparqlServer


@dataclass
class MillenniumDBConfig(ServerConfig):
    """
    MillenniumDB configuration
    """

    def __post_init__(self):
        """
        Configure the MillenniumDB-specific URLs and settings
        """
        super().__post_init__()

        # MillenniumDB uses different ports for SPARQL and Web UI
        self.sparql_port = 1234
        self.web_port = 4321

        # Configure URLs
        self.status_url = f"http://{self.host}:{self.sparql_port}/sparql"
        self.sparql_url = f"http://{self.host}:{self.sparql_port}/sparql"
        self.upload_url = None  # MillenniumDB uses mdb-import, not HTTP upload
        self.web_url = f"http://{self.host}:{self.web_port}"

    def get_docker_run_command(self, data_dir: str) -> str:
        """
        Generate docker run command for MillenniumDB server.

        Note: This starts the server. Data must be imported first using mdb-import.

        Args:
            data_dir: Host directory path containing the imported database

        Returns:
            Complete docker run command string
        """
        # The database path inside the container will be /data/<dataset>
        db_path = f"/data/{self.dataset}"

        docker_run_command = (
            f"docker run -d --name {self.container_name} "
            f"-p {self.sparql_port}:1234 "
            f"-p {self.web_port}:4321 "
            f"-v {data_dir}:/data "
            f"{self.image} "
            f"mdb-server {db_path}"
        )
        return docker_run_command


class MillenniumDB(SparqlServer):
    """
    Dockerized MillenniumDB SPARQL server

    MillenniumDB uses a two-step process:
    1. Import data with mdb-import to create database
    2. Run server with mdb-server pointing to created database
    """

    def __init__(self, config: ServerConfig, env: ServerEnv):
        """
        Initialize the MillenniumDB manager.

        Args:
            config: Server configuration
            env: Server environment (includes log, shell, debug, verbose)
        """
        super().__init__(config=config, env=env)

    def pre_create(self):
        """
        Import data using mdb-import before starting the server.
        This is MillenniumDB's unique two-step setup process.
        """
        data_dir = Path(self.config.base_data_dir)
        data_dir.mkdir(parents=True, exist_ok=True)

        db_dir = data_dir / self.config.dataset

        # Check if database already exists
        catalog_file = db_dir / "catalog.dat"
        if catalog_file.exists():
            self.log.log(
                "✅",
                self.config.container_name,
                f"Database already exists at {db_dir}"
            )
            return

        # Find RDF files to import
        dumps_dir = Path(self.config.dumps_dir) if self.config.dumps_dir else data_dir
        rdf_files = list(dumps_dir.glob(f"*{self.rdf_format.extension}"))

        if not rdf_files:
            self.log.log(
                "⚠️",
                self.config.container_name,
                f"No RDF files found in {dumps_dir}"
            )
            # Create empty database anyway
            import_files = []
        else:
            import_files = [str(f) for f in rdf_files]

        # Run mdb-import to create database
        self.log.log(
            "✅",
            self.config.container_name,
            f"Importing {len(import_files)} files into database..."
        )

        # Build import command
        # Map both dumps_dir and data_dir to container
        files_arg = " ".join([f"/import/{Path(f).name}" for f in import_files])

        import_cmd = (
            f"docker run --rm "
            f"-v {dumps_dir}:/import "
            f"-v {data_dir}:/data "
            f"{self.config.image} "
            f"mdb-import {files_arg} /data/{self.config.dataset}"
        )

        import_result = self.shell.run(import_cmd, tee=self.verbose)

        if import_result.returncode != 0:
            self.log.log(
                "❌",
                self.config.container_name,
                f"Import failed: {import_result.stderr}"
            )
            raise RuntimeError(f"mdb-import failed: {import_result.stderr}")

        self.log.log(
            "✅",
            self.config.container_name,
            f"Database created at {db_dir}"
        )

    def status(self) -> ServerStatus:
        """
        Get server status information.

        Returns:
            ServerStatus object with status information
        """
        server_status = super().status()

        if server_status.exists and server_status.running:
            # Check if SPARQL endpoint is responding
            response = self.make_request(
                "POST",
                self.config.sparql_url,
                headers={"Content-Type": "application/sparql-query"},
                data="SELECT * WHERE { ?s ?p ?o } LIMIT 1"
            )

            if response.success:
                server_status.at = ServerLifecycleState.READY
                server_status.http_status_code = response.response.status_code
                self.add_triple_count2_server_status(server_status)
            elif response.error:
                server_status.at = ServerLifecycleState.ERROR
                server_status.error = response.error

        return server_status

    def upload_request(self, file_content: bytes) -> Response:
        """
        MillenniumDB doesn't support HTTP upload.
        Data must be imported using mdb-import before server starts.

        This method will raise an error if called.
        """
        error_msg = (
            "MillenniumDB does not support HTTP upload. "
            "Data must be imported using mdb-import before starting the server. "
            "Place RDF files in the dumps_dir and restart the server."
        )
        self.log.log("❌", self.config.container_name, error_msg)
        return Response(None, RuntimeError(error_msg))

    def load_dump_files(self, file_pattern: str = None) -> int:
        """
        Override load_dump_files to explain MillenniumDB's import process.

        For MillenniumDB, data must be imported during database creation,
        not after the server is running. This method will restart the server
        with a fresh import if called.
        """
        self.log.log(
            "ℹ️",
            self.config.container_name,
            "MillenniumDB requires data import before server start. Restarting with fresh import..."
        )

        # Stop and remove existing container
        self.stop()
        self.rm()

        # Remove existing database directory to force reimport
        db_dir = Path(self.config.base_data_dir) / self.config.dataset
        if db_dir.exists():
            import shutil
            shutil.rmtree(db_dir)
            self.log.log(
                "✅",
                self.config.container_name,
                f"Removed existing database at {db_dir}"
            )

        # Start will trigger pre_create which does the import
        started = self.start()

        if started:
            # Count triples to verify import
            count = self.count_triples()
            self.log.log(
                "✅",
                self.config.container_name,
                f"Database imported with {count:,} triples"
            )
            return 1  # Return 1 to indicate success
        else:
            return 0

    def get_web_url(self) -> str:
        """
        Return the MillenniumDB Web UI URL.
        """
        return self.config.web_url